// layout.js (Server Component)
'use client';
import { Roboto } from 'next/font/google';
import React from 'react';
import './globals.css';
import Header from './_component/Header';
import Footer from './_component/Footer';
import BodyClassManager from './_component/BodyClassManager';  // Client component
import {
  ClerkProvider,
  // SignInButton,
  // SignedIn,
  // SignedOut,
  // UserButton
} from '@clerk/nextjs'
import { CartContext } from './_context/CartContext';
const inter = Roboto({ subsets: ['latin'], weight: ['400', '700'] });

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({ children }) {
  const [cart, setCart] = React.useState([]);
  
  return (
    <ClerkProvider>
      <CartContext.Provider value={{cart, setCart}}>
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning>
        <BodyClassManager />
        <Header />
        {/* <SignedOut>
            <SignInButton />
          </SignedOut>
          <SignedIn>
            <UserButton />
          </SignedIn> */}
        {children}
        <Footer />
      </body>
    </html>
    </CartContext.Provider>
    </ClerkProvider>
  );
}
